spring:
  application.name: Chlora
  datasource:
    url: jdbc:postgresql://103.150.92.246:5432/chlora
    username: chlora
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true

mqtt:
  config:
    broker-url: tcp://103.150.92.246:1883
    client-id: chlora-sub-12345
    username: chlora
    password: root
  subscriber:
    topic: chlora/+/sensors
    qos: 1

security:
  jwt:
    secret: vHhRhIyNrMU9lUAO1LvBpSLHIDY3sLPpQUuoz/aq296jlmRnUY3WMeN3yvoJ0Pa/wlFtIwaiEyMq380BuGDg7w==

telegram:
  config:
    bot-token: 8691907573:AAGXKVLXPq-gqA-I781NAf-ys7CSJd25pBw
    chat-id: "-1003817135707"

ml:
  service:
    url: http://chlora-ml:8082