-- =============================================================
-- V3 : devices
-- Owned by management.device module.
-- References clusters via cluster_id (business key — no FK
-- across module boundaries; integrity enforced at application
-- layer via ClusterExistencePort).
-- =============================================================

CREATE TABLE devices (
    id          BIGSERIAL    PRIMARY KEY,
    device_id   VARCHAR(24)  NOT NULL UNIQUE,
    device_name VARCHAR(255) NOT NULL,
    device_type VARCHAR(64)  NOT NULL,
    status      VARCHAR(16)  NOT NULL DEFAULT 'OFFLINE'
     CHECK (status IN ('ONLINE', 'OFFLINE')),
    cluster_id  VARCHAR(16)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
deleted_at  TIMESTAMPTZ
);

CREATE INDEX idx_devices_device_id   ON devices (device_id);
CREATE INDEX idx_devices_cluster_id  ON devices (cluster_id);
CREATE INDEX idx_devices_status      ON devices (status);
CREATE INDEX idx_devices_deleted_at  ON devices (deleted_at);

COMMENT ON TABLE  devices             IS 'IoT sensor nodes (ESP32 devices).';
COMMENT ON COLUMN devices.device_id  IS 'Business-facing ID generated by application layer.';
COMMENT ON COLUMN devices.cluster_id IS 'References clusters.cluster_id; no DB-level FK (cross-module).';
COMMENT ON COLUMN devices.status     IS 'ONLINE | OFFLINE';
COMMENT ON COLUMN devices.deleted_at IS 'NULL means active; soft-delete pattern.';
